### PR TITLE
Implement tagged unions for sealed traits

### PR DESCRIPTION
**Pull request by vincentdehaan**
This PR implements tagged unions for sealed traits. 
For example:
```scala
sealed trait Foo
case class Bar(s: String) extends Foo
case class Baz(s: String) extends Foo
```
translates to:
```typescript
export interface IBar {
  s: string
  type: "Bar"
}
export interface IBaz {
  s: string
  type: "Baz"
}
export type Foo = (IBar | IBaz)
```
The name of the discriminator field can be changed, and the feature can be disabled for compatibility purposes.

### CODE REVIEW

**Comment by dhoepelman** [comment]
Thanks for the PR, tagged unions are insanely common and thus useful to support. Fixes #50 

I took a look at your PR and have a bit of difficulty with modifying `TSUnion` for this to add the boolean, while a type being DU has nothing to do with the union itself:
```
type SchrodingersDiscriminatedUnion= A | B
// Current representation: TSAlias("SchrodingersDiscriminatedUnion", Seq(ref("A"),ref("B")))

// With this definition the union is not a DU
type A = string
type B = number

// With this definition it is
interface A {
  type: 'A'
}
interface B {
  type: 'B'
}
```
This means that ideally a `TSUnion` is totally oblivious to whether it's a DU or not, since it's an emergent property and not something just with the union itself (which would merit adding a field).

With your PR, when looking at `SchrodingersDiscriminatedUnion`, the representation should have `tagged = false` in the one case and `tagged = true` in the other. Suddenly you can't just look at a snippet of Typescript code and create the corresponding Scala representation. That can lead to difficulties and bugs.

So how could this be done instead? The right place for this is the macro. `fromSealed` should add some meta-information, which the serializer can pickup and treat like an extra field for interfaces.

Luckily such a meta-wrapper already exist in `TSTypeReference`, where this can be added:
```
    * @param discriminator the discrimininator value for the type if this type is part of a discriminated union
  case class TSTypeReference(name: String, impl: Option[TypescriptType] = None, discriminator: Option[TypescriptType] = None) extends TypescriptNamedType with TypescriptAggregateType {
```

this can then be used by the serializer to add the right field, and by the macro to add the information:
```
val operands = children map { symbol =>
       q"TypescriptType.nameOrType(${getTSType(symbol.asType.toType)}.get, discriminator = symbol.name.toString)"
}
```

If you modify the PR with this or solve the changes in another way* I'll review again, otherwise I'll try this myself when I get around to it™

\* The ideal castle-in-a-cloud solution would be the macro should add the underlying `TSInterface` representation's to add a `$kind: 'XXX'` field, where `$kind` is the configurable SBT property, but I don't think that's doable.

**Review by dhoepelman — CHANGES_REQUESTED** [review]
see comment above

**Comment by vincentdehaan** [comment]
I updated the code according to your request, fixed a few things and improved the tests, and I rebased onto master.

**Review by dhoepelman — APPROVED** [review]
Awesome, thank you

**Pull request merged**
